# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'old_proposal' label to any change within the 00_old_proposal folder
old_proposal:
  - 00_old_one_from_proposal/**

# Add 'simple_controller_plus_agent' label to any change within the 01_simple_controller_plus_agent folder
simple_controller_plus_agent:
  - 01_simple_controller_plus_agent/**

# Add 'docker_file_connecting_agent_and_controller' label to any change within the 02_custom_docker_file_connecting_agent_and_controller folder
docker_file_connecting_agent_and_controller:
  - 02_custom_docker_file_connecting_agent_and_controller/**

# Add 'maven_tutorial' label to any change within the 03_maven_tutorial folder
maven_tutorial:
  - 03_maven_tutorial/**

# Add 'python_tutorial' label to any change within the 04_python_tutorial folder
python_tutorial:
  - 04_python_tutorial/**

# Add 'nodejs' label to any change within the 05_nodejs folder
nodejs:
  - 05_nodejs/**

# Add 'test' label to any change to test* files within the github dir
test:
- .github/workflows/test-**.yml

# Add 'docker' label to any change to Dockerfile* files within the root dir
docker:
- any: ['/**/Dockerfile']

# Add 'docker_compose' label to any change to docker-compose* files within the root dir
docker_compose:
- any: ['/**/docker-compose*.yml']

# Add 'github_actions' label to any change to .github/workflows/* files within the root dir
github_actions:
- any: ['/.github/workflows/*']