services:
  jenkins_controller: 
    build: dockerfiles/.
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - type: bind
        source: ./secrets/jenkins_agent_ed
        target: /run/secrets/SSH_AGENT_KEY
        read_only: true
    
  jenkins_agent:
    image: jenkins/ssh-agent:5.5.0-jdk17
    container_name: desktop-jenkins_agent-1
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOrE9ruJy21SwqbC/RUnFU5zfwgoj/w+1tYCpgx1aLrx jh@jh-Modern-14-B5M
volumes: 
  jenkins_home:
