services:
  jenkins_controller: 
    build: dockerfiles/.
    restart: on-failure
    environment:
      - JENKINS_EXT_URL=${JENKINS_EXT_URL:-http://localhost:8080} # Default to localhost:8080 with HTTP
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - type: bind
        source: ./secrets/jenkins_agent_ed
        target: /run/secrets/SSH_AGENT_KEY
        read_only: true
    
  jenkins_agent:
    build: dockerfiles/agent/.
    container_name: desktop-jenkins_agent-1
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvD2vnWO1Dqcxj/tfgpr2mKO8QJmkfhDhvTolrLk14U jh@jh-Modern-14-B5M
volumes: 
  jenkins_home:
