name: docker image building and pushing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ '*' ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Will build everyday at 4:30 and 16:30
    - cron:  '30 4,16 * * *'

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      docker-ignore: ${{ steps.filter.outputs.docker-ignore }}
      gradle-wrapper: ${{ steps.filter.outputs.gradle-wrapper }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
            docker-ignore:
              - '.dockerignore'

  docker:
    # Wait from the paths-filter to be completed before starting next-job
    needs: paths-filter
    if: "!contains(needs.paths-filter.changes.outputs, '[]')"
    # “!contains(toJson(github.event.pull_request.labels), ‘[]’)”
    runs-on: ubuntu-latest
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -e 's#/#-#g')"
        id: extract_branch
      -
        name: Build and push a simple bundled instance
        uses: docker/build-push-action@v4
        with:
          context: ./00_old_one_from_proposal
          platforms: linux/amd64, linux/aarch64
          push: true
          tags: gounthar/jenkinsci-tutorials:bundled_instance_${{ steps.extract_branch.outputs.branch }}
      -
        name: Build and push a simple jenkins controller
        uses: docker/build-push-action@v4
        with:
          context: ./02_custom_docker_file_connecting_agent_and_controller/dockerfiles/Dockerfile
          platforms: linux/amd64, linux/aarch64
          push: true
          tags: gounthar/jenkinsci-tutorials:simple_controller_${{ steps.extract_branch.outputs.branch }}
      -
        name: Build and push the jenkins controller for maven tutorial
        uses: docker/build-push-action@v4
        with:
          context: ./03_maven_tutorial/dockerfiles/Dockerfile
          platforms: linux/amd64, linux/aarch64
          push: true
          tags: gounthar/jenkinsci-tutorials:maven_controller_${{ steps.extract_branch.outputs.branch }}
      -
        name: Build and push the jenkins agent for maven tutorial
        uses: docker/build-push-action@v4
        with:
          context: ./03_maven_tutorial/dockerfiles/agent/Dockerfile
          platforms: linux/amd64, linux/aarch64
          push: true
          tags: gounthar/jenkinsci-tutorials:maven_agent_${{ steps.extract_branch.outputs.branch }}

